In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
tumour=pd.read_csv("experment.csv");
print(tumour)

      age  gender  city  asbestos exposure  type of MM  \
0    47.0       1     0                  1         0.0   
1    55.0       1     0                  1         0.0   
2    29.0       1     1                  1         0.0   
3    39.0       1     0                  1         0.0   
4    47.0       1     0                  1         0.0   
..    ...     ...   ...                ...         ...   
319  75.0       1     1                  1         0.0   
320  66.0       1     1                  1         0.0   
321  58.0       1     6                  1         0.0   
322  42.0       1     6                  0         0.0   
323  54.0       1     0                  1         0.0   

     duration of asbestos exposure  diagnosis method  keep side  cytology  \
0                             20.0                 1          0         1   
1                             45.0                 1          0         0   
2                             23.0                 0          1         

In [5]:
print(tumour.columns)

Index(['age', 'gender', 'city', 'asbestos exposure', 'type of MM',
       'duration of asbestos exposure', 'diagnosis method', 'keep side',
       'cytology', 'duration of symptoms', 'dyspnoea', 'ache on chest',
       'weakness', 'habit of cigarette', 'performance status', 'white blood',
       'cell count (WBC)', 'hemoglobin (HGB)', 'platelet count (PLT)',
       'sedimentation', 'blood lactic dehydrogenise (LDH)',
       'alkaline phosphatise (ALP)', 'total protein', 'albumin', 'glucose',
       'pleural lactic dehydrogenise', 'pleural protein', 'pleural albumin',
       'pleural glucose', 'dead or not', 'pleural effusion',
       'pleural thickness on tomography', 'pleural level of acidity (pH)',
       'C-reactive protein (CRP)', 'class of diagnosis'],
      dtype='object')


In [6]:
import seaborn as sns
tumour.head()

age  gender  city  asbestos exposure  type of MM  \
0  47.0       1     0                  1         0.0   
1  55.0       1     0                  1         0.0   
2  29.0       1     1                  1         0.0   
3  39.0       1     0                  1         0.0   
4  47.0       1     0                  1         0.0   

   duration of asbestos exposure  diagnosis method  keep side  cytology  \
0                           20.0                 1          0         1   
1                           45.0                 1          0         0   
2                           23.0                 0          1         0   
3                           10.0                 1          0         0   
4                           10.0                 1          1         1   

   duration of symptoms  ...  pleural lactic dehydrogenise  pleural protein  \
0                  24.0  ...                         289.0              0.0   
1                   1.0  ...                        7541.0              1.6   
2                   1.0  ...                         480.0              0.0   
3                   3.0  ...                         459.0              5.0   
4                   1.5  ...                         213.0              3.6   

   pleural albumin  pleural glucose  dead or not  pleural effusion  \
0             0.00             79.0            1               0.0   
1             0.80              6.0            1               1.0   
2             0.00             90.0            1               0.0   
3             2.80             45.0            1               1.0   
4             1.95             53.0            1               1.0   

   pleural thickness on tomography  pleural level of acidity (pH)  \
0                              0.0                            0.0   
1                              1.0                            1.0   
2                              0.0                            0.0   
3                              0.0                            0.0   
4                              0.0                            0.0   

   C-reactive protein (CRP)  class of diagnosis  
0                        34                   1  
1                        42                   1  
2                        43                   2  
3                        21                   1  
4                        11                   1  

[5 rows x 35 columns]

In [13]:
X=tumour.iloc[:,:-1].values
y=tumour.iloc[:,4].values
print(X)
print(y)

[[47.  1.  0. ...  0.  0. 34.]
 [55.  1.  0. ...  1.  1. 42.]
 [29.  1.  1. ...  0.  0. 43.]
 ...
 [58.  1.  6. ...  0.  1. 68.]
 [42.  1.  6. ...  1.  0. 78.]
 [54.  1.  0. ...  1.  0. 45.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 2.
 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.
 0. 0

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [11]:
y_pred=classifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        65

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65

[[65]]
